# Generated by Django 5.1.2 on 2024-10-11 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_request', '0003_servicerequestmodel_service_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequestmodel',
            name='file',
            field=models.FileField(null=True, upload_to='requests/'),
        ),
        migrations.AlterField(
            model_name='servicerequestmodel',
            name='service_type',
            field=models.CharField(choices=[('maintainance', 'Maintainance'), ('refill', 'Refill'), ('leakage', 'Leakage'), ('exchange', 'Exchange'), ('payment', 'Payment'), ('other', 'Other')], max_length=20),
        ),
    ]
